<?php

declare(strict_types=1);

namespace Drupal\Tests\emulsify_tools\Integration\ThemeGeneration;

use Drupal\Core\Extension\ThemeExtensionList;
use Drupal\emulsify_tools\ThemeGeneration\EmulsifyThemeGenerator;
use Drupal\emulsify_tools\ThemeGeneration\ThemeGenerationRequest;
use Drupal\emulsify_tools\ThemeGeneration\ThemeGenerationResult;
use Drupal\emulsify_tools\ThemeGeneration\ThemeGeneratorInterface;
use Drupal\Tests\UnitTestCase;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Symfony\Component\Filesystem\Filesystem;

/**
 * Tests selection of the Emulsify child-theme generation strategy.
 */
#[CoversClass(EmulsifyThemeGenerator::class)]
#[Group('emulsify_tools')]
final class EmulsifyThemeGeneratorTest extends UnitTestCase {

  /**
   * Filesystem helper.
   */
  private Filesystem $filesystem;

  /**
   * Temporary Drupal application root.
   */
  private string $appRoot;

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();

    $this->filesystem = new Filesystem();
    $this->appRoot = sys_get_temp_dir() . '/emulsify_tools_strategy_' . bin2hex(random_bytes(8));
    $this->filesystem->mkdir($this->appRoot);
  }

  /**
   * {@inheritdoc}
   */
  protected function tearDown(): void {
    if (isset($this->appRoot) && $this->filesystem->exists($this->appRoot)) {
      $this->filesystem->remove($this->appRoot);
    }

    parent::tearDown();
  }

  /**
   * Tests valid Drupal Starterkit metadata selects the core generator.
   */
  public function testValidModernSourceSelectsStarterkitGenerator(): void {
    $this->writeWhiskSource(
      $this->validInfoFile(),
      "info: {}\n",
      TRUE,
    );
    $request = $this->createRequest();
    $expected = new ThemeGenerationResult(0, ['Generated by Drupal Starterkit.']);

    $starterkitGenerator = $this->createMock(ThemeGeneratorInterface::class);
    $starterkitGenerator->expects($this->once())
      ->method('generate')
      ->with($request)
      ->willReturn($expected);

    $legacyFactoryCalls = 0;
    $generator = $this->createGenerator(
      $starterkitGenerator,
      function () use (&$legacyFactoryCalls): ThemeGeneratorInterface {
        $legacyFactoryCalls++;
        return $this->createMock(ThemeGeneratorInterface::class);
      },
    );

    self::assertSame($expected, $generator->generate($request));
    self::assertSame(0, $legacyFactoryCalls);
  }

  /**
   * Tests a legacy-only Emulsify 6.x marker selects the legacy generator.
   */
  public function testLegacyOnlySourceSelectsLegacyGenerator(): void {
    $this->writeWhiskSource(NULL, NULL, TRUE);
    $request = $this->createRequest();
    $expected = new ThemeGenerationResult(0, ['Generated by the legacy generator.']);

    $starterkitGenerator = $this->createMock(ThemeGeneratorInterface::class);
    $starterkitGenerator->expects($this->never())->method('generate');

    $legacyGenerator = $this->createMock(ThemeGeneratorInterface::class);
    $legacyGenerator->expects($this->once())
      ->method('generate')
      ->with($request)
      ->willReturn($expected);
    $legacyFactoryCalls = 0;
    $generator = $this->createGenerator(
      $starterkitGenerator,
      static function () use (&$legacyFactoryCalls, $legacyGenerator): ThemeGeneratorInterface {
        $legacyFactoryCalls++;
        return $legacyGenerator;
      },
    );

    self::assertSame($expected, $generator->generate($request));
    self::assertSame(1, $legacyFactoryCalls);
  }

  /**
   * Tests an ordinary core failure never triggers the legacy fallback.
   */
  public function testStarterkitFailureDoesNotFallBackToLegacyGenerator(): void {
    $this->writeWhiskSource(
      $this->validInfoFile(),
      "info: {}\n",
      TRUE,
    );
    $request = $this->createRequest();
    $expected = new ThemeGenerationResult(1, ['Drupal Starterkit failed.']);

    $starterkitGenerator = $this->createMock(ThemeGeneratorInterface::class);
    $starterkitGenerator->expects($this->once())
      ->method('generate')
      ->with($request)
      ->willReturn($expected);
    $legacyFactoryCalls = 0;
    $generator = $this->createGenerator(
      $starterkitGenerator,
      function () use (&$legacyFactoryCalls): ThemeGeneratorInterface {
        $legacyFactoryCalls++;
        return $this->createMock(ThemeGeneratorInterface::class);
      },
    );

    self::assertSame($expected, $generator->generate($request));
    self::assertSame(0, $legacyFactoryCalls);
  }

  /**
   * Tests incomplete or malformed modern metadata never selects legacy.
   */
  #[DataProvider('incompleteModernSourceProvider')]
  public function testIncompleteModernSourceDoesNotSelectLegacy(
    ?string $infoContents,
    ?string $starterkitContents,
  ): void {
    $this->writeWhiskSource($infoContents, $starterkitContents, TRUE);
    $request = $this->createRequest();
    $expected = new ThemeGenerationResult(1, ['Invalid Drupal Starterkit source.']);

    $starterkitGenerator = $this->createMock(ThemeGeneratorInterface::class);
    $starterkitGenerator->expects($this->once())
      ->method('generate')
      ->with($request)
      ->willReturn($expected);
    $legacyFactoryCalls = 0;
    $generator = $this->createGenerator(
      $starterkitGenerator,
      function () use (&$legacyFactoryCalls): ThemeGeneratorInterface {
        $legacyFactoryCalls++;
        return $this->createMock(ThemeGeneratorInterface::class);
      },
    );

    self::assertSame($expected, $generator->generate($request));
    self::assertSame(0, $legacyFactoryCalls);
  }

  /**
   * Provides incomplete and malformed modern source combinations.
   *
   * @return array<string, array{string|null, string|null}>
   *   Source metadata keyed by scenario.
   */
  public static function incompleteModernSourceProvider(): array {
    $validInfo = <<<YAML
name: Whisk Starter
type: theme
base theme: emulsify
core_version_requirement: '^11.3 || ^12'
version: 7.x-dev
YAML . "\n";

    return [
      'missing starterkit config' => [$validInfo, NULL],
      'orphan starterkit config' => [NULL, "info: {}\n"],
      'malformed starterkit config' => [$validInfo, "info: [\n"],
      'malformed info file' => ["name: [\n", "info: {}\n"],
    ];
  }

  /**
   * Creates the strategy generator under test.
   */
  private function createGenerator(
    ThemeGeneratorInterface $starterkitGenerator,
    \Closure $legacyFactory,
  ): EmulsifyThemeGenerator {
    $themeExtensionList = $this->createMock(ThemeExtensionList::class);
    $themeExtensionList->method('exists')
      ->with('emulsify')
      ->willReturn(TRUE);
    $themeExtensionList->method('getPath')
      ->with('emulsify')
      ->willReturn('themes/contrib/emulsify');

    return new EmulsifyThemeGenerator(
      $themeExtensionList,
      $starterkitGenerator,
      $legacyFactory,
      $this->appRoot,
    );
  }

  /**
   * Creates the generation request used by each strategy scenario.
   */
  private function createRequest(): ThemeGenerationRequest {
    return new ThemeGenerationRequest(
      machineName: 'happy_theme',
      displayName: 'Happy Theme',
      description: 'Project theme.',
      starterkitMachineName: 'whisk',
      destinationPath: 'themes/custom',
    );
  }

  /**
   * Writes a Whisk source with the requested format markers.
   */
  private function writeWhiskSource(
    ?string $infoContents,
    ?string $starterkitContents,
    bool $includeLegacyMarker,
  ): void {
    $directory = $this->appRoot . '/themes/contrib/emulsify/whisk';
    $this->filesystem->mkdir($directory);

    if ($infoContents !== NULL) {
      $this->filesystem->dumpFile($directory . '/whisk.info.yml', $infoContents);
    }
    if ($starterkitContents !== NULL) {
      $this->filesystem->dumpFile($directory . '/whisk.starterkit.yml', $starterkitContents);
    }
    if ($includeLegacyMarker) {
      $this->filesystem->dumpFile(
        $directory . '/whisk.info.emulsify.yml',
        "name: whisk\ntype: theme\nbase theme: emulsify\n",
      );
    }
  }

  /**
   * Returns valid modern Whisk theme metadata.
   */
  private function validInfoFile(): string {
    return <<<YAML
name: Whisk Starter
type: theme
base theme: emulsify
core_version_requirement: '^11.3 || ^12'
version: 7.x-dev
YAML . "\n";
  }

}
